#!/bin/bash
wget https://download.docker.com/linux/debian/dists/stretch/pool/stable/amd64/docker-ce_17.12.0~ce-0~debian_amd64.deb
sudo dpkg -i docker-ce_17.12.0~ce-0~debian_amd64.deb
#docker build -t debian9-ansible
docker pull geerlingguy/docker-debian9-ansible:latest
docker run --detach --privileged --volume=/sys/fs/cgroup:/sys/fs/cgroup:ro geerlingguy/docker-debian9-ansible:latest /lib/systemd/systemd
docker exec --tty [container_id] env TERM=xterm ansible --version