#!/bin/bash
sudo apt-get update
sudo apt-get install libqt5opengl5 libqt5printsupport5 psmisc linux-headers-686 linux-headers-4.9.0-4-686
sudo dpkg -i virtualbox-5.2_5.2.6-120293~Debian~stretch_i386.deb
sudo dpkg -i vagrant_2.0.2_i686.deb
git clone https://github.com/mongalless/vagrant-workarea.git
cd vagrant-workarea && vagrant up